import { ArrowLeft, ArrowRight, BadgeCheck, ExternalLink, Globe2, Mail, UserRound, XCircle } from 'lucide-react';
import type { CreatorRecord } from '@/features/import/model/import.types';
import { SidePanel } from '@/shared/components/SidePanel';
import { ScoreMetric } from '@/shared/components/ScoreMetric';
import { formatNumber } from '@/shared/lib/normalize';
import type { CreatorDecision } from '../model/creator.model';

interface CreatorDetailProps { record: CreatorRecord; decision?: CreatorDecision; position: number; total: number; onClose(): void; onPrevious(): void; onNext(): void; onDecision(decision: CreatorDecision | null): void; }

function LinkButton({ href, label }: { href: string; label: string }) { return href ? <a className="contact-button" href={href} target="_blank" rel="noopener noreferrer"><Globe2 size={15} />{label}<ExternalLink size={13} /></a> : null; }

export function CreatorDetail({ record, decision, position, total, onClose, onPrevious, onNext, onDecision }: CreatorDetailProps) {
  const evidence = [['Content fit', record.contentFitEvidence], ['Audience & engagement', record.audienceEngagementEvidence], ['Authority & opinion strength', record.authorityOpinionEvidence], ['Access & partnership viability', record.accessPartnershipEvidence], ['Observed activity', record.observedActivityEvidence], ['Partnership angle', record.partnershipAngleEvidence]];
  const pipeline = Boolean(record.status || record.firstContact || record.channel || record.lastTouch || record.touches !== null || record.callDate || record.callOutcome || record.dealPotential);
  return <SidePanel eyebrow={`${record.category || 'Creator'} · ${position + 1} of ${total}`} title={record.creatorName} onClose={onClose} footer={<><div className="panel-pagination"><button type="button" onClick={onPrevious} disabled={position === 0}><ArrowLeft size={15} /> Previous</button><button type="button" onClick={onNext} disabled={position === total - 1}>Next <ArrowRight size={15} /></button></div><div className="decision-buttons"><button type="button" className={decision === 'Not approved' ? 'decision is-negative' : 'decision'} onClick={() => onDecision(decision === 'Not approved' ? null : 'Not approved')}><XCircle size={15} /> Not approved</button><button type="button" className={decision === 'Approved' ? 'decision is-positive' : 'decision'} onClick={() => onDecision(decision === 'Approved' ? null : 'Approved')}><BadgeCheck size={15} /> Approve</button></div></>}>
    <section className="detail-hero"><span className="creator-avatar creator-avatar--large"><UserRound /></span><div><p>{[record.creatorType, record.subcategory].filter(Boolean).join(' · ') || 'Creator profile'}</p><span><Globe2 size={14} />{record.region || 'Region not provided'}{record.language && ` · ${record.language}`}</span></div><div className="detail-total"><strong>{record.sourceTotalScore ?? '—'}</strong><small>Total score</small>{record.tier && <span className="tier-badge">{record.tier}</span>}</div></section>
    <section className="detail-section"><div className="section-heading"><div><p className="eyebrow">Qualification</p><h3>Creator assessment</h3></div></div><div className="detail-score-grid"><ScoreMetric label="Content fit" value={record.contentFit} /><ScoreMetric label="Audience & engagement" value={record.audienceEngagement} /><ScoreMetric label="Authority & opinion strength" value={record.authorityOpinion} /><ScoreMetric label="Access & partnership viability" value={record.accessPartnership} /></div></section>
    <section className="detail-section"><div className="section-heading"><div><p className="eyebrow">Reach and identity</p><h3>Audience footprint</h3></div></div><dl className="definition-grid"><div><dt>Audience</dt><dd>{formatNumber(record.audienceSize)}</dd></div><div><dt>Total likes</dt><dd>{formatNumber(record.totalLikes)}</dd></div><div><dt>Video count</dt><dd>{formatNumber(record.videoCount)}</dd></div><div><dt>Primary platform</dt><dd>{record.primaryPlatform || '—'}</dd></div><div><dt>Agency</dt><dd>{record.agency || '—'}</dd></div><div><dt>DM viable</dt><dd>{record.dmViable === null ? 'Unknown' : record.dmViable ? 'Yes' : 'No'}{record.dmQualifier && ` · ${record.dmQualifier}`}</dd></div></dl>{record.descriptionNotes && <div className="long-copy"><small>Description notes</small><p>{record.descriptionNotes}</p></div>}</section>
    <section className="detail-section"><div className="section-heading"><div><p className="eyebrow">Contact and channels</p><h3>Available routes</h3></div></div><div className="contact-person"><UserRound /><div><strong>{record.contactName || 'Contact not provided'}</strong><span>{record.agency || 'No agency provided'}</span></div></div><div className="contact-button-grid">{record.emails.map(email => <a className="contact-button" href={`mailto:${email}`} key={email}><Mail size={15} />{email}</a>)}<LinkButton href={record.linkInBio} label="Link in bio" /><LinkButton href={record.tiktokUrl} label="TikTok" /><LinkButton href={record.instagramUrl} label="Instagram" /><LinkButton href={record.youtubeUrl} label="YouTube" /><LinkButton href={record.twitterUrl} label="X / Twitter" />{record.otherPlatformUrls.map((url, index) => <LinkButton key={url} href={url} label={`Other platform ${index + 1}`} />)}</div>{record.otherPlatform && <p className="callout"><strong>Other platform source:</strong> {record.otherPlatform}</p>}</section>
    <section className="detail-section"><div className="section-heading"><div><p className="eyebrow">Partnership thesis</p><h3>Research and recommended angle</h3></div></div><div className="thesis-stack"><article><small>Observed activity</small><p>{record.observedActivity || 'Not provided'}</p></article><article><small>Partnership angle</small><p>{record.partnershipAngle || 'Not provided'}</p></article><article><small>Outreach angle</small><p>{record.outreachAngle || 'Not provided'}</p></article>{record.highLevelNotes && <article><small>High-level notes</small><p>{record.highLevelNotes}</p></article>}</div></section>
    <section className="detail-section"><div className="section-heading"><div><p className="eyebrow">Evidence</p><h3>Research supporting the assessment</h3></div></div><div className="evidence-list">{evidence.map(([label, value]) => <details key={label}><summary>{label}<span>{value ? 'Available' : 'Not provided'}</span></summary><p>{value || 'No evidence was supplied for this field.'}</p></details>)}</div></section>
    <section className="detail-section"><div className="section-heading"><div><p className="eyebrow">Pipeline</p><h3>Outreach and conversion</h3></div></div>{pipeline ? <dl className="definition-grid"><div><dt>Status</dt><dd>{record.status || '—'}</dd></div><div><dt>First contact</dt><dd>{record.firstContact || '—'}</dd></div><div><dt>Channel</dt><dd>{record.channel || '—'}</dd></div><div><dt>Last touch</dt><dd>{record.lastTouch || '—'}</dd></div><div><dt>Touches</dt><dd>{record.touches ?? '—'}</dd></div><div><dt>Call date</dt><dd>{record.callDate || '—'}</dd></div><div><dt>Call outcome</dt><dd>{record.callOutcome || '—'}</dd></div><div><dt>Deal potential</dt><dd>{record.dealPotential || '—'}</dd></div></dl> : <p className="empty-inline">No outreach has been recorded in the source workbook.</p>}</section>
    {record.warnings.length > 0 && <section className="detail-section"><div className="section-heading"><div><p className="eyebrow">Data quality</p><h3>Source notes</h3></div></div><ul className="warning-list">{record.warnings.map((warning, index) => <li key={`${warning}-${index}`}>{warning}</li>)}</ul></section>}
  </SidePanel>;
}
